# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myseq <- function(first, last) {
    .Call('_CADF_myseq', PACKAGE = 'CADF', first, last)
}

zeros <- function(x) {
    .Call('_CADF_zeros', PACKAGE = 'CADF', x)
}

ones <- function(len) {
    .Call('_CADF_ones', PACKAGE = 'CADF', len)
}

create_discount_vector <- function(amount, duration, discountrate) {
    .Call('_CADF_create_discount_vector', PACKAGE = 'CADF', amount, duration, discountrate)
}

calculate_St_vector <- function(r) {
    .Call('_CADF_calculate_St_vector', PACKAGE = 'CADF', r)
}

retention_simulator <- function(MonthlyPayment, DiscountRate, NumberMonths, RetentionRates) {
    .Call('_CADF_retention_simulator', PACKAGE = 'CADF', MonthlyPayment, DiscountRate, NumberMonths, RetentionRates)
}

